# -*- coding: utf-8 -*-
"""ML model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n_MYb9-walSHR6MHLirWFRjlLw98JuDz

Import Library
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import classification_report

"""EDA"""

data=pd.read_csv('/content/diabetes.csv')
data

data.info()

data.describe()

data.isnull().sum()

#pairplot using sns
sns.pairplot(data, diag_kind='kde')

"""Seperate the labels and target"""

X=data.drop('Outcome',axis=1)
y=data['Outcome']

X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2,random_state=42)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

"""Fit the model"""

model=LogisticRegression()
model.fit(X_train,y_train)

y_predict=model.predict(X_test)
score=model.score(X_test,y_test)
print(score)

#confusion matrix.
cmf_test=confusion_matrix(y_test,y_predict)

cmf_test_Score=ConfusionMatrixDisplay(cmf_test)
cmf_test_Score.plot()

import pickle

pickle.dump(model,open('model.pkl','wb+'))